[package]
name = "pi-system-logging"
version = "0.1.0"
authors = ["Max Jöhnk <maxjoehnk@gmail.com>"]

[dependencies]
influent = "0.4"
failure = "0.1.1"
regex = "1.0.1"
strum = "0.10.0"
strum_macros = "0.10.0"
serde = "1.0"
serde_derive = "1.0"
toml = "0.4"